Curate/format dates
nextstrain/rsv pull request #34
Opened 2023-08-15 18:47 UTC by j23414

### Description of proposed changes

As part of an ongoing migration of transform scripts to `augur curate` subcommands, this PR moves to replace the titlecase and format-dates scripts with their corresponding augur curate subcommands:

* [augur curate titlecase](https://docs.nextstrain.org/projects/augur/en/stable/usage/cli/curate/titlecase.html)
* [augur curate format-dates](https://docs.nextstrain.org/projects/augur/en/stable/usage/cli/curate/format-dates.html)

During the process of manual testing, an issue related to multiple headers in the fetched data was identified and resolved. This PR includes those changes.

### Related issue(s)

### Testing

- [ ] Checks pass

For a manual check, could run:

```
git clone https://github.com/nextstrain/rsv.git
cd rsv/ingest
git checkout curate/format-dates
nextstrain build . data/a/metadata.tsv
```

2023-08-18 23:12 UTC, joverlee521 requested changes
The switch over to the new `augur curate` commands look good to me! 

I've left a comment for an alternative solution to the header lines issue, which is more "snakemake-y" and allows us to parallelize the rules.

2023-08-18 23:12 UTC, joverlee521 commented on ingest/workflow/snakemake_rules/fetch_sequences.smk
Oh interesting, I just realized this pipeline uses hard-coded URLs from the config 🤔 

---

I think we could use Snakemake wildcards to parallelize `fetch_from_genbank` and `csv_to_ndjson` for the different URLs and then combine the NDJSONs in the `fetch_all_sequences` rule.

(Currently, it seems like the `fetch_all_sequences` rule is just making an extra copy for no apparent reason)

2023-08-22 10:25 UTC, j23414 commented on ingest/workflow/snakemake_rules/fetch_sequences.smk
I fully support the transition to using Snakemake wildcards, etc.

The corresponding `ncbi-taxon-ids` would be as follows:

```
208893
208895
11250
```

2023-08-22 13:38 UTC, j23414 commented on ingest/workflow/snakemake_rules/fetch_sequences.smk
The transition to Snakemake wildcards are added in bab8cee09e52c0d5dc9b7e5eb0426c9c5e482c51

Can test on this branch with the following dry-run:

```
cd ingest
nextstrain build  . -np data/sequences.ndjson
```

But do let me know if I've misinterpreted anything.

2023-08-22 23:59 UTC, joverlee521 commented on ingest/workflow/snakemake_rules/fetch_sequences.smk
Ah thanks for updating! Looks like this copies over the scripts I'm currently adding in https://github.com/nextstrain/ingest/pull/16. Would you mind waiting for that to be merged and we can just pull in the vendored scripts to use here?

2023-08-23 05:17 UTC, j23414 commented on ingest/workflow/snakemake_rules/fetch_sequences.smk
Oh! I'd prefer using the vendored scripts here instead of having duplicates. I don't mind waiting.

2023-09-12 23:00 UTC, joverlee521 commented on ingest/workflow/snakemake_rules/fetch_sequences.smk
Sorry we lost momentum on this! With the latest [issue with NCBI Virus](https://github.com/nextstrain/rsv/issues/36), I'm going to update the ingest to use NCBI Datasets in a separate change. Will circle back here once I'm done with that.

2023-09-15 16:02 UTC, j23414 commented on ingest/workflow/snakemake_rules/fetch_sequences.smk
Rebased to incorporate NCBI datasets, I see the transition to Snakemake wildcards, thanks!
Ready for review.

2023-09-15 16:41 UTC, joverlee521 approved these changes
Changes look good to me from inspection!

I triggered a [trial run for the ingest](https://github.com/nextstrain/rsv/actions/runs/6200629194) and we can do a diff with the production data to make sure nothing has changed.

2023-09-15 17:47 UTC, joverlee521 commented
Trial run completed successfully and uploaded outputs to `s3://nextstrain-data/files/workflows/rsv/trial/curate-format-dates/*`. I compared the output metadata TSV files with the production files on S3 and there were no differences in the existing data, just a couple of new records for rsv/b that's been added since the last automated run. 

<details>
<summary>
Compared outputs with the current files with:
</summary>

```
ingest/vendored/download-from-s3 s3://nextstrain-data/files/workflows/rsv/trial/curate-format-dates/a/metadata.tsv.gz ingest/data/test-run/a-metadata.tsv
ingest/vendored/download-from-s3 s3://nextstrain-data/files/workflows/rsv/a/metadata.tsv.gz ingest/data/a-metadata.tsv
daff diff ingest/data/a-metadata.tsv ingest/data/test-run/a-metadata.tsv > /tmp/rsv-a-metadata.tsv.diff

ingest/vendored/download-from-s3 s3://nextstrain-data/files/workflows/rsv/trial/curate-format-dates/b/metadata.tsv.gz ingest/data/test-run/b-metadata.tsv
ingest/vendored/download-from-s3 s3://nextstrain-data/files/workflows/rsv/b/metadata.tsv.gz ingest/data/b-metadata.tsv
daff diff ingest/data/b-metadata.tsv ingest/data/test-run/b-metadata.tsv > /tmp/rsv-b-metadata.tsv.diff
```


</details>

2023-09-15 19:22 UTC, merged